# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!

target 'NewOO' do
    pod 'SnapKit'
    pod 'IQKeyboardManagerSwift'
    pod 'Charts'
end
